controller_list:
# name和action_ns组成控制器action接口的消息名，例如arm_controller插件的action接口就是:arm_controller/follow_joint_trajectory
  - name: arm_controller  # 控制器插件的名称
    action_ns: follow_joint_trajectory  # 控制器发布action消息的命名空间
    type: FollowJointTrajectory  # 实现action的类型
    default: true  # 是否为该规划组的默认控制器插件
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      
  - name: gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true # 是否为该规划组的默认控制器插件
    joints:
      - finger_joint1
      
